import { ComplianceEvaluationInput } from "./types";

export const SAMPLE_COMPLIANCE_INPUT: ComplianceEvaluationInput = {
  inspectionId: "DEMO-INS-2026-001",
  productId: "PRD-ALOO-BHUJIA-400G",
  productName: "Haldiram's Nagpur Aloo Bhujia (400g)",
  brand: "Haldiram's",
  metadata: {
    category: "Packaged Food",
    packageType: "Retail Pack",
    isImported: false,
    isEcommerceListing: false,
    productDate: "2026-01-10",
    netQuantityValue: 400,
    netQuantityUnit: "g",
    hasPhysicalScaleCalibration: false, // demonstrates Font-Size uncalibrated -> REVIEW!
  },
  declarationResult: {
    productId: "PRD-ALOO-BHUJIA-400G",
    sourceType: "PACKAGE_IMAGE",
    sourceImages: ["/sample_package_back.jpg"],
    overallExtractionConfidence: 0.94,
    extractionTimestamp: "2026-09-11T10:30:00.000Z",
    extractionEngine: "LabelGuard Bilingual Semantic OCR v2.1",
    category: "Packaged Food",
    categoryConfidence: 0.98,
    warnings: [],
    isDemo: true,
    fields: [
      {
        id: "FLD-01",
        fieldType: "PRODUCT_NAME",
        labelKey: "declarations.fields.product_name",
        rawText: "ALOO BHUJIA नमकीन",
        normalizedValue: "Aloo Bhujia Namkeen",
        language: "mixed",
        confidence: 0.98,
        status: "DETECTED",
        sourceOcrItemIds: ["OCR-001"],
        sourceType: "PACKAGE_IMAGE",
        boundingBox: { x: 12.5, y: 8.2, width: 75.0, height: 6.5 },
      },
      {
        id: "FLD-02",
        fieldType: "BRAND",
        labelKey: "declarations.fields.brand",
        rawText: "HALDIRAM'S",
        normalizedValue: "Haldiram's",
        language: "en",
        confidence: 0.99,
        status: "DETECTED",
        sourceOcrItemIds: ["OCR-002"],
        sourceType: "PACKAGE_IMAGE",
        boundingBox: { x: 35.0, y: 3.5, width: 30.0, height: 4.2 },
      },
      {
        id: "FLD-03",
        fieldType: "NET_QUANTITY",
        labelKey: "declarations.fields.net_quantity",
        rawText: "Net Wt. / शुद्ध मात्रा : 400 g",
        normalizedValue: "400 g",
        language: "mixed",
        confidence: 0.96,
        status: "DETECTED",
        sourceOcrItemIds: ["OCR-003"],
        sourceType: "PACKAGE_IMAGE",
        boundingBox: { x: 10.0, y: 22.0, width: 38.0, height: 4.8 },
      },
      {
        id: "FLD-04",
        fieldType: "QUANTITY_UNIT",
        labelKey: "declarations.fields.quantity_unit",
        rawText: "g",
        normalizedValue: "g",
        language: "en",
        confidence: 0.98,
        status: "DETECTED",
        sourceOcrItemIds: ["OCR-003"],
        sourceType: "PACKAGE_IMAGE",
      },
      {
        id: "FLD-05",
        fieldType: "MRP",
        labelKey: "declarations.fields.mrp",
        rawText: "MRP ₹110.00 (inclusive of all taxes)",
        normalizedValue: "₹110.00",
        language: "en",
        confidence: 0.97,
        status: "DETECTED",
        sourceOcrItemIds: ["OCR-004"],
        sourceType: "PACKAGE_IMAGE",
        boundingBox: { x: 55.0, y: 22.0, width: 40.0, height: 5.0 },
      },
      {
        id: "FLD-06",
        fieldType: "TAX_WORDING",
        labelKey: "declarations.fields.tax_wording",
        rawText: "inclusive of all taxes",
        normalizedValue: "inclusive of all taxes",
        language: "en",
        confidence: 0.95,
        status: "DETECTED",
        sourceOcrItemIds: ["OCR-004"],
        sourceType: "PACKAGE_IMAGE",
      },
      {
        id: "FLD-07",
        fieldType: "PRICE_TEXT",
        labelKey: "declarations.fields.unit_sale_price",
        rawText: "Unit Sale Price: ₹ 0.28 / g",
        normalizedValue: "₹ 0.28 / g",
        language: "en",
        confidence: 0.93,
        status: "DETECTED",
        sourceOcrItemIds: ["OCR-005"],
        sourceType: "PACKAGE_IMAGE",
        boundingBox: { x: 55.0, y: 28.0, width: 38.0, height: 4.0 },
      },
      {
        id: "FLD-08",
        fieldType: "MANUFACTURE_DATE",
        labelKey: "declarations.fields.manufacture_date",
        rawText: "MFD: 01/2026",
        normalizedValue: "01/2026",
        language: "en",
        confidence: 0.94,
        status: "DETECTED",
        sourceOcrItemIds: ["OCR-006"],
        sourceType: "PACKAGE_IMAGE",
        boundingBox: { x: 10.0, y: 35.0, width: 35.0, height: 4.5 },
      },
      {
        id: "FLD-09",
        fieldType: "BEST_BEFORE",
        labelKey: "declarations.fields.best_before",
        rawText: "Best Before 6 Months from Packaging",
        normalizedValue: "07/2026",
        language: "en",
        confidence: 0.91,
        status: "DETECTED",
        sourceOcrItemIds: ["OCR-007"],
        sourceType: "PACKAGE_IMAGE",
        boundingBox: { x: 10.0, y: 41.0, width: 45.0, height: 4.5 },
      },
      {
        id: "FLD-10",
        fieldType: "MANUFACTURER_NAME",
        labelKey: "declarations.fields.manufacturer_name",
        rawText: "Mfg by: Haldiram Foods International Pvt. Ltd.",
        normalizedValue: "Haldiram Foods International Pvt. Ltd.",
        language: "en",
        confidence: 0.96,
        status: "DETECTED",
        sourceOcrItemIds: ["OCR-008"],
        sourceType: "PACKAGE_IMAGE",
        boundingBox: { x: 10.0, y: 52.0, width: 80.0, height: 4.5 },
      },
      {
        id: "FLD-11",
        fieldType: "MANUFACTURER_ADDRESS",
        labelKey: "declarations.fields.manufacturer_address",
        rawText: "Plot No. 145/146, Old Pardi Naka, Bhandara Road, Nagpur - 440035, Maharashtra, India",
        normalizedValue: "Plot No. 145/146, Old Pardi Naka, Bhandara Road, Nagpur - 440035, Maharashtra, India",
        language: "en",
        confidence: 0.95,
        status: "DETECTED",
        sourceOcrItemIds: ["OCR-009"],
        sourceType: "PACKAGE_IMAGE",
        boundingBox: { x: 10.0, y: 57.0, width: 80.0, height: 7.0 },
      },
      {
        id: "FLD-12",
        fieldType: "CONSUMER_CARE_PHONE",
        labelKey: "declarations.fields.consumer_care_phone",
        rawText: "Toll Free: 1800-209-4455",
        normalizedValue: "1800-209-4455",
        language: "en",
        confidence: 0.97,
        status: "DETECTED",
        sourceOcrItemIds: ["OCR-010"],
        sourceType: "PACKAGE_IMAGE",
        boundingBox: { x: 10.0, y: 72.0, width: 40.0, height: 4.5 },
      },
      {
        id: "FLD-13",
        fieldType: "CONSUMER_CARE_EMAIL",
        labelKey: "declarations.fields.consumer_care_email",
        rawText: "customercare@haldirams.com",
        normalizedValue: "customercare@haldirams.com",
        language: "en",
        confidence: 0.98,
        status: "DETECTED",
        sourceOcrItemIds: ["OCR-011"],
        sourceType: "PACKAGE_IMAGE",
        boundingBox: { x: 52.0, y: 72.0, width: 43.0, height: 4.5 },
      },
      {
        id: "FLD-14",
        fieldType: "CONSUMER_CARE_ADDRESS",
        labelKey: "declarations.fields.consumer_care_address",
        rawText: "Customer Care Cell, Nagpur - 440035",
        normalizedValue: "Customer Care Cell, Nagpur - 440035",
        language: "en",
        confidence: 0.94,
        status: "DETECTED",
        sourceOcrItemIds: ["OCR-012"],
        sourceType: "PACKAGE_IMAGE",
      },
      {
        id: "FLD-15",
        fieldType: "BATCH_NUMBER",
        labelKey: "declarations.fields.batch_number",
        rawText: "BATCH NB-260105",
        normalizedValue: "NB-260105",
        language: "en",
        confidence: 0.92,
        status: "DETECTED",
        sourceOcrItemIds: ["OCR-013"],
        sourceType: "PACKAGE_IMAGE",
        boundingBox: { x: 10.0, y: 84.0, width: 35.0, height: 4.5 },
      },
    ],
  },
};
